### PR TITLE
Goal is now dependent on BuildGoal

### LINKED ISSUE #21: Maven deployer per branch goal should wait on build goal
When autofixes are applied, the deployment now fails with a lot of output in the feed. Use a goal depending on the BuildGoal

### PR DESCRIPTION
**Pull request by lievendoclo**
resolves #21

### CODE REVIEW

File: lib/java/deploy/MavenPerBranchSpringBootDeploymentGoal.ts [hunk 1]
```diff
@@ -8,7 +8,7 @@
  *     http://www.apache.org/licenses/LICENSE-2.0
  *
  * Unless required by applicable law or agreed to in writing, software
- * distributed under the License is distributed on an "AS IS" BASIS,
+ * distributed under the License is distributed on #an "AS IS" BASIS,
```
Comment (cdupuis) [inline lib/java/deploy/MavenPerBranchSpringBootDeploymentGoal.ts]: ???
